default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: password
  host: 127.0.0.1
  port: 5432
development:
  <<: *default
  database: life_glow

test:
  <<: *default
  database: your_test_database_name
